### ISSUE TITLE
[Question] instructions for usage?

### ISSUE THREAD

**Issue by scheung38** [chenhunghan/lens-ext-invaders#3]
After

yarn build
yarn run v1.22.10
$ npm run clean && webpack
npm WARN lifecycle The node binary used for scripts is /var/folders/r1/p68hfp513tdd08hq3s1jdrmw0000gn/T/yarn--1610250078214-0.6830913260309341/node but npm is using /usr/local/Cellar/node@12/12.18.2/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @lensapp/lens-ext-invaders@0.0.1 clean $HOME/Documents/GitHub/lens-ext-invaders
> rm -rf ./dist

Hash: 2a009561a5f7b257f9655ae5c7412995bd7479e3
Version: webpack 4.44.2
Child
    Hash: 2a009561a5f7b257f965
    Time: 388ms
    Built at: 01/10/2021 3:41:19 AM
      Asset     Size  Chunks             Chunk Names
    main.js  6.5 KiB    main  [emitted]  main
    Entrypoint main = main.js
    [./main.ts] 616 bytes {main} [built]
    [@k8slens/extensions] external "global.LensExtensions" 42 bytes {main} [built]
Child
    Hash: 5ae5c7412995bd7479e3
    Time: 1590ms
    Built at: 01/10/2021 3:41:21 AM
          Asset     Size  Chunks             Chunk Names
    renderer.js  2.1 MiB    main  [emitted]  main
    Entrypoint main = renderer.js
    [./renderer.tsx] 1.69 KiB {main} [built]
    [@k8slens/extensions] external "global.LensExtensions" 42 bytes {main} [built]
    [react] external "global.React" 42 bytes {main} [built]
        + 10 hidden modules

➜  lens-ext-invaders git:(main) ✗ ln -s ~/lens-ext-invaders ~/.k8slens/extensions/lens-ext-invaders

what to do next to play this game? Thanks

**Comment by chenhunghan** [comment]
Next step is to open Lens and you will see "space invader" in cluster menu (on the left side of Lens window).

**Comment by dnaprawa** [comment]
@chenhunghan if I want to use it on Windows, is there an option? How to produce tar,tgz file? I see in Lens GUI it's possible to select extension package (tar,tgz).

**Comment by chenhunghan** [comment]
@dnaprawa I add a new section in README, you can grab the .tgz file from release and install 
https://github.com/chenhunghan/lens-ext-invaders/blob/main/README.md#install
